version: '3.4'

networks:
  frontend:
  backend:

services:
  productcatalogapi:
    image: productcatalogapi
    build:
      context: .\ProductCatalogApi
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:7910
      DatabaseServer: mymssqlserver
      DatabaseName: EventDB
      DatabaseUser: sa
      DatabasePassword: P@ssword(!)
    ports: 
      - "7910:80"
    networks: 
     - frontend
     - backend
    depends_on:
      - mymssqlserver
    container_name: EventsServer

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: jewels/tokenapi1
    environment:
      MvcClient: http://localhost:7911
    ports:
     - "7900:80"
    container_name: tokenserviceapi
    networks:
     - backend
     - frontend
    depends_on:
     - mymssqlserver 

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: jewels/cartapi
    environment:
      IdentityUrl: http://10.0.0.113:7900
      ConnectionString: basket.data
    ports:
     - "7920:80"
    container_name: cartapi
    networks:
     - backend
     - frontend
    depends_on:
     - tokenserver
     - basket.data

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: jewels/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      IdentityUrl: http://10.0.0.113:7900
      DatabaseServer: mymssqlserver
      DatabaseName: EventDB
      DatabaseUser: sa
      DatabasePassword: P@ssword(!)
    ports:
     - "7930:80"
    container_name: orderapi
    networks:
     - frontend
     - backend
    depends_on:
     - mymssqlserver
     - tokenserver

  webmvc1:
    image: jewels/webmvc1
    build: 
      context: .\WebMvc1
      dockerfile: Dockerfile
    environment:
      EventUrl: http://productcatalogapi
      IdentityUrl: http://10.0.0.113:7900
      CallBackUrl: http://localhost:7911
      CartUrl: http://cart
    ports: 
     - "7911:80"
    container_name: webshop1
    networks:
     - frontend
    depends_on: 
     - productcatalogapi
     - tokenserver
     - cart
     - order

  mymssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssword(!)
    ports:
      - "1548:1433"
    container_name: mymssqlserver
    networks:
     - backend

  basket.data:
    image: redis
    container_name: basketdata
    ports:
     - "7090:6379"
    networks:
     - backend
    

