version: '3.4'

networks:
  frontend:
  backend:

services:
  productcatalogapi:
    image: productcatalogapi
    build:
      context: .\ProductCatalogApi
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:7810
      DatabaseServer: mymssqlserver
      DatabaseName: EventDB
      DatabaseUser: sa
      DatabasePassword: P@ssword(!)
    ports: 
      - "7910:80"
    networks: 
     - frontend
     - backend
    depends_on:
      - mymssqlserver
    container_name: EventsServer

  webmvc1:
    image: jewels/webmvc1
    build: 
      context: .\WebMvc1
      dockerfile: Dockerfile
    environment:
      EventUrl: http://productcatalogapi
    ports: 
     - "7911:80"
    container_name: webshop1
    networks:
     - frontend
    depends_on: 
     - productcatalogapi
      

  mymssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssword(!)
    ports:
      - "1548:1433"
    container_name: mymssqlserver
    networks:
     - backend

